version: '2'
services:
  eddi_keycloak:
    image: jboss/keycloak-mongo
    links:
      - eddi_mongodb
    ports:
      - 8080:8080
    environment:
    #env var should be placed in docker-compose.override and not commmitted to svn for security reasons
    #each env should come with its own defined docker-compose.override file
       - MONGODB_DBNAME=keycloak
       - MONGO_PORT_27017_TCP_ADDR=eddi_mongodb
#used to join the same network as nlp and mongoDB containers (their hosts are connected and available to each other )
networks:
  default:
    external:
      name: eddi_default